{% set name = "viu" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/atanunq/viu/archive/v{{ version }}.tar.gz
  sha256: 9682be1561f7a128436bd2e45d1f8f7146ca1dd7f528a69bd3c171e4e855474b

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - viu --help

about:
  home: https://github.com/atanunq/viu
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Simple terminal image viewer written in Rust
  dev_url: https://github.com/atanunq/viu

extra:
  recipe-maintainers:
    - danielnachun
