{% set name = "viu" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/atanunq/viu/archive/v{{ version }}.tar.gz
  sha256: bd1bc61367420dcbb1ab46df53a46fd7d35379960c9ab39bbccb7ace5afaeb62

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - viu --help

about:
  home: https://github.com/atanunq/viu
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Simple terminal image viewer written in Rust
  dev_url: https://github.com/atanunq/viu

extra:
  recipe-maintainers:
    - danielnachun
