context:
  version: "1.6.0"

package:
  name: viu
  version: ${{ version }}

source:
  url: https://github.com/atanunq/viu/archive/v${{ version }}.tar.gz
  sha256: 2164d8626b8210227ded514a0ca18fc4092571e174f55905facd33837fe2eb4c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - viu --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Simple terminal image viewer written in Rust
  homepage: https://github.com/atanunq/viu
  repository: https://github.com/atanunq/viu

extra:
  recipe-maintainers:
    - danielnachun
